### ISSUE TITLE
using vosk-model-cn-kaldi-cvte-2 model alway connect error

### ISSUE THREAD

**Issue by fingerx** [IlgarLunin/vosk-language-server#3]
hi thanks for update but using vosk-model-cn-kaldi-cvte-2 is always error othes models is ok
(using your ue plugin)

**Comment by fingerx** [comment]
![image](https://user-images.githubusercontent.com/5524551/143665584-7f963056-3cad-4721-9214-a476e435a309.png)

using vosk-model-cn-kaldi-cvte-2 show:
![image](https://user-images.githubusercontent.com/5524551/143665668-d5ce41c4-11a6-452a-9602-f5484bd29830.png)

**Comment by IlgarLunin** [comment]
Do not change ip address in vls, leave it 0.0.0.0 and try different port maybe

**Comment by fingerx** [comment]
1.![image](https://user-images.githubusercontent.com/5524551/143726067-ffae0a0b-d067-4377-8510-435203d5f26d.png)

2.
![image](https://user-images.githubusercontent.com/5524551/143726085-90c8418a-2941-4180-bb03-95c7c5f2bcbd.png)


all same setting but vosk-model-cn-kaldi-cvte-2 cant work,alway show socket connect failed

**Comment by IlgarLunin** [comment]
@fingerx  can you please attach link where to download this model, will try to reproduce the problem

**Comment by fingerx** [comment]
@IlgarLunin https://alphacephei.com/vosk/models/vosk-model-cn-kaldi-cvte-2.zip

**Comment by fingerx** [comment]
@IlgarLunin  want to know any news,thanks

**Comment by IlgarLunin** [comment]
@fingerx just tested it, and all works as expected

https://user-images.githubusercontent.com/8058622/144050218-ffa07078-78d5-4073-a8c6-4da06c4fd000.mp4

Problem might be be caused by 1988 port. Check if this port is free on your machine, I recommend [this utility](https://www.nirsoft.net/utils/cports.html)

**Comment by fingerx** [comment]
thanks, this my mistake.....
